### ISSUE TITLE
How can I change the port 8080 within the docker container

### ISSUE THREAD

**Issue by JaniceXiong** [UCREL/science_parse_py_api#1]
Hi, Thanks a lot for wrapping Science Parse using python. I pull your docker in https://hub.docker.com/r/ucrel/ucrel-science-parse. But when I use the command trying to change port from 8080 to 8081, it seems still running on the default 8080 port.
![image](https://user-images.githubusercontent.com/43976565/137322662-cd5c79a7-9992-4255-8893-5704ff124403.png)
And when I use the code below trying to parse pdf like given example, ConnectionError always appear and docker server have nothing to response.
![image](https://user-images.githubusercontent.com/43976565/137324006-a28bc1af-f704-4257-8f47-a45d7e9ee531.png)

- On port 8080:

URL: http://127.0.0.1:8080/v1. 56196.pdf failed due to the following error:
Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f723a2c2910>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f723a2c2910>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/science_parse_api/api.py", line 49, in parse_pdf
    response = requests.post(url, files=files,
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f723a2c2910>: Failed to establish a new connection: [Errno 111] Connection refused'))
None

- On port 8081
URL: http://127.0.0.1:8081/v1. 56196.pdf failed due to the following error:
Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/home/xjw/miniconda3/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/science_parse_api/api.py", line 49, in parse_pdf
    response = requests.post(url, files=files,
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/xjw/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
None

@apmoore1 Hope these problems do not disturb you. Thanks :)

**Comment by apmoore1** [comment]
Hi, I think the following docker command should solve your problem:
``` bash
docker run -p 127.0.0.1:8081:8080 --rm --init ucrel/ucrel-science-parse:3.0.1
```

With this command the science parse server within the docker container will use port 8080, however this port will be mapped to port 8081 on your local machine. I have tested your code using this command and it works on my Ubuntu machine. Hope this solves your problem if not let me know and I will try and help.
